name: Deploy Node Application

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: docker build -t sirijupally/nodejs-app  .
      - name: Publish Image to docker hub
        run: docker push sirijupally/nodejs-app:latest 
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Clean up docker space
        run: docker system prune -f
      - name: Pull image from docker hub
        run: docker pull  sirijupally/nodejs-app:latest 
      - name: Delete old container
        run: docker rm -f nodejs-app-container  
      - name: Run Docker Container
        run: |
          docker run -d \
            -p 4000:4000 \
            --name nodejs-app-container \
            -e AWS_REGION='ap-south-1' \
            -e AWS_ACCESS_KEY_ID='${{ secrets.AWS_ACCESS_KEY_ID }}' \
            -e AWS_SECRET_ACCESS_KEY='${{ secrets.AWS_SECRET_ACCESS_KEY }}' \
            -e S3_BUCKET_NAME='resrishti' \
            -e MONGO_URI=mongodb+srv://jupally_siri:${{ secrets.MONGO_PASSWORD }}@cluster1.rtxdwgf.mongodb.net/?appName=cluster1 \
            -e JWT_SECRET='${{ secrets.JWT_SECRET }}' \
            -e SMTP_HOST='smtp.gmail.com' \
            -e SMTP_PORT='587' \
            -e SMTP_USER='siri21.jupally@gmail.com' \
            -e SMTP_PASS='${{ secrets.SMTP_PASS }}' \
            -e FROM_EMAIL='siri21.jupally@gmail.com' \
            -e CLIENT_URL='http://localhost:5173' \
            -e SERVER_URL='http://localhost:5000' \
            -e NODE_ENV='production' \
            -e VAPID_PUBLIC_KEY='BJxnYrTfAhkQFtbXOIKC1SFXUd5rc2tB_2vgiaV2dzVWGS8OSVRZDwpsRoP2Jojr_LQGvKCVLKgCNgyFfA-Ed8A' \
            -e VAPID_PRIVATE_KEY='XzAeIms4QojUrLDz9E2cKhs5-fbpDTQ0KZfv4svO1Kk' \
            -e VAPID_MAILTO='mailto:admin@resrishti.com' \
            sirijupally/nodejs-app
