/*
  Certificate model — Client Management module (Phase 1, Chunk 3)

  Purpose:
  - Represents a Certificate of Disposal (CoD) — a legal document issued to a
    client confirming that waste delivered to Resrishti was processed.
  - One certificate per pickup in the happy path; on data corrections, a NEW
    certificate is issued with `revision: prev+1` and `supersedes: oldCertId`,
    while the old one stays downloadable for audit (status = 'superseded').

  Lifecycle (clientmngmt.md §8.2):
      draft  ──issue──▶  issued  ──send──▶  sent  ──revise──▶  superseded
                                                                   │
                                                                   ▼
                                                            new draft (revision+1)

  Snapshots:
  - Once a certificate hits `issued`, the snapshot fields below are immutable.
    They live on the cert itself (not just the pickup) so that even if the
    underlying pickup/client data is later edited, the legal record is stable.
  - `lineItemsSnapshot` is a deliberate subset of `Pickup.lineItems` — only
    `stream` + `qtyKg` (the weighbridge photo isn't reproduced into the cert).

  Coordination note for parallel agents:
  - Backend G (THIS chunk) creates the cert in `draft` status with snapshots
    populated, sets `pickup.certificate = cert._id`, and flips pickup status
    to `cert-draft`. See `recordWasteData` in supervisorPickupController.
  - Backend H (PDF + issue/send) reads `lineItemsSnapshot` / `totalKgSnapshot`
    / `clientNameSnapshot` / `pickupDateSnapshot` to render the PDF. Issue
    sets `status='issued'`, `issuedAt/By`, and `pdf` after S3 upload. Send
    sets `status='sent'`, `sentAt/By`. NEITHER agent ever touches `certNumber`
    after this chunk hands the draft off.
  - Backend I (client portal cert list/download + public stats) only READS
    this model.

  Indexes:
  - `certNumber` is uniquely indexed (declared via `unique: true` on the field).
  - `{ client: 1, status: 1 }` for the client portal "My Certificates" tab
    and the manager review queue.
  - `{ pickup: 1 }` for the one-to-one (or one-to-N via revisions) lookup
    from a pickup detail page.
*/

const mongoose = require("mongoose");

const certificateSchema = new mongoose.Schema(
    {
        // Format: `CoD-YYYY-####` (4-digit zero-padded, see clientmngmt.md §11.3).
        // Generated by utils/certNumber.js — atomic via the Counter model.
        // NOT field-level unique: revisions share the certNumber. Uniqueness
        // is enforced by the compound (certNumber, revision) index below.
        certNumber: { type: String, required: true },

        // Starts at 1. Bumped only on revision (Agent H's revise endpoint).
        revision: { type: Number, default: 1 },

        // Set on the NEW cert when it revises an older one. Null on the
        // original. The old cert's status flips to 'superseded' at that point.
        supersedes: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Certificate",
            default: null,
        },

        pickup: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Pickup",
            required: true,
        },
        client: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Client",
            required: true,
        },

        status: {
            type: String,
            enum: ["draft", "issued", "sent", "superseded"],
            default: "draft",
        },

        // --- Immutable snapshots (frozen at issuance) -----------------------
        // Kept here so the cert PDF can be regenerated identically even if
        // the underlying pickup/client data is later edited.
        lineItemsSnapshot: [
            {
                stream: String,
                qtyKg: Number,
                _id: false,
            },
        ],
        totalKgSnapshot: Number,
        clientNameSnapshot: String,
        pickupDateSnapshot: Date,

        // S3 location of the rendered PDF. Filled by Agent H at `issue` time.
        // `cods/<YYYY>/<certNumber>.pdf` per spec §11.2.
        pdf: {
            key: String,
            bucket: String,
            _id: false,
        },

        // Audit fields — actor snapshots so the cert remains readable even
        // if the manager user later leaves the org.
        issuedAt: Date,
        issuedBy: {
            userType: String,
            userId: mongoose.Schema.Types.ObjectId,
            name: String,
            _id: false,
        },
        sentAt: Date,
        sentBy: {
            userType: String,
            userId: mongoose.Schema.Types.ObjectId,
            name: String,
            _id: false,
        },
    },
    { timestamps: true }
);

// Indexes — see clientmngmt.md §6.4.
// Uniqueness on (certNumber, revision) — different revisions legitimately
// share the same certNumber (one is 'sent', the rest 'superseded'/'draft').
// A field-level `unique: true` on certNumber alone would block revision
// creation, so we use a compound index instead.
certificateSchema.index({ certNumber: 1, revision: 1 }, { unique: true });
certificateSchema.index({ client: 1, status: 1 });
certificateSchema.index({ pickup: 1 });

module.exports = mongoose.model("Certificate", certificateSchema);
