/*
  Counter model — Client Management module (Phase 1, Chunk 3)

  Purpose:
  - Provides an atomic, monotonically-increasing numeric sequence keyed by an
    arbitrary string. Used initially for certificate numbering (key shape
    `cert-<YYYY>`) but kept generic so any future scope needing a clean
    monotonic ID (invoice numbers, manifest numbers, etc.) can reuse it.

  Atomicity note:
  - The `nextValue` static MUST be implemented as a single round-trip
    `findOneAndUpdate` with `$inc` + `upsert: true`. A read-then-write
    pattern would race under any concurrent traffic and reissue duplicate
    certificate numbers — which is unrecoverable for a legal document.
  - The unique index on `key` (declared via `unique: true` on the field) plus
    the upsert guarantees that two simultaneous calls for the same key end up
    serialized by MongoDB; both return distinct `value`s.

  Coordination note for parallel agents:
  - Agent H (PDF rendering / cert issue) does NOT call `Counter` directly —
    the cert number is generated by `utils/certNumber.js` at draft time
    (see `recordWasteData` in supervisorPickupController). Agent H reads the
    already-assigned certNumber off the draft.
*/

const mongoose = require("mongoose");

const counterSchema = new mongoose.Schema(
    {
        // Sequence key, e.g. 'cert-2026'. Unique index lives here on the field.
        key: { type: String, required: true, unique: true },
        // Current value of the sequence. `nextValue` always returns the
        // post-increment value (so the FIRST call returns 1, not 0).
        value: { type: Number, required: true, default: 0 },
    },
    { timestamps: true }
);

/**
 * Atomically increment and return the next value for `key`.
 *
 * Implementation detail: the `$setOnInsert: { key }` is technically redundant
 * (the filter already pins `key`) but it makes the intent explicit for anyone
 * scanning the file — when this upserts, the new document gets that key.
 *
 * @param {string} key - Sequence key, e.g. 'cert-2026'.
 * @returns {Promise<number>} The new value AFTER the increment (1 on first call).
 */
counterSchema.statics.nextValue = async function (key) {
    const doc = await this.findOneAndUpdate(
        { key },
        { $inc: { value: 1 }, $setOnInsert: { key } },
        { new: true, upsert: true }
    );
    return doc.value;
};

module.exports = mongoose.model("Counter", counterSchema);
